name: CondenserWand
main: com.majestic.condenserwand.CondenserWand
version: 1.0.3
author: MajesticFaucet
softdepend: [WorldGuard]
commands:
  condenserwand:
    description: main plugin command
    usage: /condenserwand [info|version|help]